"""empty message

Revision ID: 9baa0d662a7c
Revises: c83a59af8eaf
Create Date: 2025-09-01 22:10:38.587055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9baa0d662a7c'
down_revision: Union[str, Sequence[str], None] = 'c83a59af8eaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('translations_user_id_fkey'), 'translations', type_='foreignkey')
    op.create_foreign_key(None, 'translations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'translations', type_='foreignkey')
    op.create_foreign_key(op.f('translations_user_id_fkey'), 'translations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
