"""empty message

Revision ID: 811884aac289
Revises: 
Create Date: 2025-08-27 23:05:01.068995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '811884aac289'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_word', sa.String(length=25), nullable=False),
    sa.Column('translated_word', sa.String(length=25), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'original_word', name='uq_user_original_word')
    )
    op.create_index('idx_original_translated', 'translations', ['original_word', 'translated_word'], unique=False)
    op.create_index('idx_user_created_at', 'translations', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_user_original', 'translations', ['user_id', 'original_word'], unique=False)
    op.create_index(op.f('ix_translations_original_word'), 'translations', ['original_word'], unique=False)
    op.create_index(op.f('ix_translations_translated_word'), 'translations', ['translated_word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_translated_word'), table_name='translations')
    op.drop_index(op.f('ix_translations_original_word'), table_name='translations')
    op.drop_index('idx_user_original', table_name='translations')
    op.drop_index('idx_user_created_at', table_name='translations')
    op.drop_index('idx_original_translated', table_name='translations')
    op.drop_table('translations')
    op.drop_table('users')
    # ### end Alembic commands ###
